import type {Metadata} from "next";
import "@/styles/globals.css";
import {ReactNode} from "react";
import SessionWrapper from "@/components/sessionWrapper";


export const metadata: Metadata = {
    title: 'Strava Map',
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <SessionWrapper>
            <html lang="en">
            <body>
            {children}
            </body>
            </html>
        </SessionWrapper>
    );
}
