import type {Metadata} from "next";
import "@/styles/globals.css";
import {ReactNode} from "react";
import {AuthProvider} from "@/Contexts/authContext";


export const metadata: Metadata = {
    title: 'Strava Map',
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <AuthProvider>
            <body>
            {children}
            </body>
        </AuthProvider>
        </html>
    );
}
