name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull_on_serv:
    runs-on: ubuntu-latest
    steps:

      - name: Pull git repository into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap
            git checkout main
            git pull

  start_containers:
    runs-on: ubuntu-latest
    needs: pull_on_serv

    steps:

      - name: Refresh postgres docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap
            docker compose --profile frontend --profile postgres down --rmi all
            docker compose --profile postgres up -d

      - name: Build and deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap
            docker compose --profile frontend --profile postgres up -d

  migrate_DB:
    runs-on: ubuntu-latest
    needs: start_containers

    steps:
      - name: Run database migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap/frontend
            docker exec frontend-stravamap npx prisma migrate deploy