name: Docker Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Pull git repository into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/StravaMap
            git checkout main
            git pull

#      - name: Refresh backend docker containers
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
#          script: |
#            cd /home/containers/Portfolio_web
#            docker compose --profile frontend down --rmi all
#            docker compose down --rmi all
#            docker compose up -d
#
#      - name: Build and deploy frontend
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
#          script: |
#            cd /home/containers/Portfolio_web
#            docker compose --profile frontend up -d